# Generated by Django 5.0 on 2026-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="slug",
            field=models.SlugField(blank=True, null=True, max_length=220, unique=True),
        ),
    ]
